openapi: 3.0.0

info:
  title: API Title
  description: OpenAPI specification
  version: 1.0.0

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          maxLength: 26
          example: John

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

  responses:
    GetTokens:
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: ey2ace6et98s1ncjasd
                  refreshToken:
                    type: string
                    example: def50"200"75819e4748adef0566c3b41437f2b7e3
    success:
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: success
    refreshTokenResponse:
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  authentication:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJkaHJ1dkBnbWFpbC5jb20iLCJ0b2tlbiI6IjEyODQ4NjY5YTJmN2FlNTczNTNhY2U3ZjgwODJhYzI3MDg1ZWYwYzU2NzMyYjhjMDNkOGFhY2ZkY2UzMDIzNzUiLCJpYXQiOjE2NDk4MzA5ODEsImV4cCI6MTY4MTM4ODU4MX0.BwhIAYdO0-N84q3UwxsdYtVBUgsJBfAfGnSyBXcNC9c
                      refreshToken:
                        type: string
                        example: 496005929c15685ca553e1d728bea49dd7472abb6e06d22bb8096f220240f84b
                      expireAt:
                        type: number
                        example: 1683097795

    GetLoginResponse:
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                type: object
                properties:
                  _id:
                    type: integer
                    example: 643d4d03ae23825006d11937
                  firstName:
                    type: string
                    example: John
                  lastName:
                    type: string
                    example: wick
                  profileImage:
                    type: string
                    example: http://example.com/static/file_697929e031dfb468c04126e26845f03c1610166680033.jpeg
                  type:
                    type: number
                    example: 2
                  email:
                    type: string
                    example: john@gmail.com
                  bio:
                    type: string
                    example: My best friend has a fur and a tail. Dogs are not our whole life, but they make our lives whole 🐶🙂
                  address:
                    type: string
                    example: NY, Kellogg Rd New Hartford, 24
                  latitude:
                    type: string
                    example: "21.1702"
                  longitude:
                    type: string
                    example: "21.1702"
                  auth:
                    type: object
                    properties:
                      tokenType:
                        type: string
                        example: Bearer
                      accessToken:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjo1LCJwaG9uZV9udW1iZXIiOiIrOTEgNzk5MDA1MzE3MCIsImZpcnN0X25hbWUiOiJ0ZXN0c2RzZHNkc2RzZHNkcyIsI
                      refreshToken:
                        type: string
                        example: DGptc0miW9AXKCDl6H7RMMHlDcruUbPrwOowslSHiVOyYYJeFhRW1F2XKIrrfUCRIoG1lRMUfEQKSxX3TApl1Aw6641YkAGJhi6yQgr06PrZZuPFddYBvr
                      expiresIn:
                        type: integer
                        example: 31536000
    User:
      description: Success
      content:
        application/json:
          schema:
            type: object
    UnauthorizedError:
      description: |
        - Invalid credentials
        - Expired access or refresh token
        - Revoked access or refresh token
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unauthorized
    NoContent:
      description: |
        - Empty body content
      content:
        application/json:
          schema:
            type: object
    UnprocessableEntity:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
    Conflict:
      description: Account already registered with given email
      content:
        application/json:
          schema:
            type: object
    PreconditionFailedException:
      description: Account does not exist
      content:
        application/json:
          schema:
            type: object

    GetForgotPasswordResponse:
      description: Ok
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: true
              message:
                type: string
                example: Please check your email inbox. We sent you an email with reset password link.

paths:
  /auth/login:
    post:
      summary: Login Service
      description: Login Service
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "admin@hiremate.com"
                password:
                  type: string
                  example: "123@hiremateAdmin"

      responses:
        "200":
          $ref: "#/components/responses/success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"
        "412":
          $ref: "#/components/responses/PreconditionFailedException"

  # /auth/logout:
  #   post:
  #     description: Admin Logout
  #     summary: Admin Logout
  #     tags:
  #       - Auth
  #     security:
  #       - bearerAuth: []
  #     responses:
  #       "200":
  #         $ref: "#/components/responses/success"
  #       "401":
  #         $ref: "#/components/responses/UnauthorizedError"
  #       "422":
  #         $ref: "#/components/responses/UnprocessableEntity"

  /user/all:
    get:
      summary: Get user data
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: search
          required: false
          schema:
            type: string
        - in: query
          name: perPage
          required: false
          schema:
            type: number
        - in: query
          name: page
          required: false
          schema:
            type: number
      responses:
        "200":
          $ref: "#/components/responses/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

  /user/{userId}:
    get:
      summary: Get user data from userId
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
            example: 64afac4d03c466b3a968f0d9
      responses:
        "200":
          $ref: "#/components/responses/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

  /recruiter/all:
    get:
      summary: Get recruiter data
      tags:
        - Recruiter
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: search
          required: false
          schema:
            type: string
        - in: query
          name: perPage
          required: false
          schema:
            type: number
        - in: query
          name: page
          required: false
          schema:
            type: number
      responses:
        "200":
          $ref: "#/components/responses/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

  /recruiter/{recruiterId}:
    get:
      summary: Get recruiter data from recruiterId
      description: |
        | status        | Meaning           |
        | ------------- |:-------------:|
        |  0  | ***Pending***  |
        |  1  | ***Approve***  |
        |  2  |  ***Deny***   |      
      tags:
        - Recruiter
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: recruiterId
          required: true
          schema:
            type: string
            example: 64afac4d03c466b3a968f0d9
      responses:
        "200":
          $ref: "#/components/responses/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

  /recruiter/action/{recruiterId}:
    post:
      summary: Approve/reject recruiter profile
      description: |
        | status        | Meaning           |
        | ------------- |:-------------:|
        |  1  | ***Approve***  |
        |  2  |  ***Deny***   |
      tags:
        - Recruiter
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: recruiterId
          required: true
          schema:
            type: string
            example: 64afac4d03c466b3a968f0d9
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: number
                  example: 1        
      responses:
        "200":
          $ref: "#/components/responses/User"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "422":
          $ref: "#/components/responses/UnprocessableEntity"

